name: Actions

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: clean cache
        run: npm cache clean --force
      - name: install
        run: npm ci
      - name: npm install
        run: |
          npm install

      - name: npm run build
        run: |
          npm run build --if-present
        env:
          CI: false

      - name: Add remote origin
        run: |
          git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_API_NAME }}.git
      - name: Deploy to Heroku
        run: |
          git push heroku HEAD:master -f
